
GET http://localhost:3000/players/

###
GET http://localhost:3000/players/1/

###

POST http://localhost:3000/players/
Content-Type: application/json 


{
    "playerName": "Rahul",
    "jerseyNumber": 21,
    "roles": "cricketer"
}

###

PUT http://localhost:3000/players/16/
Content-Type: application/json

{
    "playerName": "abhi",
    "jerseyNumber": 13,
    "roles": "all-rounder"
}

###
DELETE http://localhost:3000/players/15/